# iPad自动化控制系统配置文件
# 重构版本 v2.0 配置示例

# 设备连接配置
connection:
  # 连接超时时间（秒）
  timeout: 30
  # 重试次数
  retry_count: 3
  # tunneld服务端口
  tunneld_port: 5000
  # 设备UDID（可选，留空自动检测）
  device_udid: ""
  # 连接模式（usb）
  connection_mode: "usb"

# 视觉识别配置
vision:
  # 模板匹配阈值
  template_threshold: 0.8
  # 模板目录路径
  template_dir: "templates"
  # 是否启用VLM大模型识别
  enable_vlm: false
  # VLM服务提供商（openai/anthropic/google）
  vlm_provider: "openai"
  # VLM API配置
  vlm_config:
    api_key: ""
    model: "gpt-4-vision-preview"
    max_tokens: 1000
    temperature: 0.1
  # 非极大值抑制阈值
  nms_threshold: 0.3
  # 最大检测数量
  max_detections: 50
  # 截图保存配置
  screenshot:
    save_enabled: true
    save_dir: "screenshots"
    format: "png"
    quality: 95

# 自动化执行配置
automation:
  # 自动化后端（webdriver/pymobiledevice）
  backend: "webdriver"
  # WebDriverAgent配置
  webdriver:
    # WDA服务端口
    port: 8100
    # WDA服务地址
    host: "localhost"
    # 连接超时
    timeout: 60
    # 启动WDA服务
    auto_start: true
  # pymobiledevice配置
  pymobiledevice:
    # 触控延迟（秒）
    touch_delay: 0.1
    # 滑动持续时间（秒）
    swipe_duration: 0.5
  # 通用操作配置
  actions:
    # 操作间延迟（秒）
    delay: 0.5
    # 点击持续时间（秒）
    click_duration: 0.1
    # 长按持续时间（秒）
    long_press_duration: 1.0
    # 滑动速度（像素/秒）
    swipe_speed: 1000

# 任务管理配置
task:
  # 任务执行超时（秒）
  execution_timeout: 300
  # 最大并发任务数
  max_concurrent_tasks: 1
  # 任务重试次数
  retry_count: 3
  # 任务历史保留数量
  history_limit: 100
  # 条件检查间隔（秒）
  condition_check_interval: 1.0

# 日志配置
logging:
  # 日志级别（DEBUG/INFO/WARNING/ERROR/CRITICAL）
  level: "DEBUG"
  # 控制台输出
  console:
    enabled: true
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    color: true
  # 文件输出
  file:
    enabled: true
    path: "logs/ipad_automation.log"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s"
    # 文件大小限制
    max_size: "10MB"
    # 备份文件数量
    backup_count: 5
    # 日志轮转
    rotation: "daily"
  # 性能日志
  performance:
    enabled: true
    path: "logs/performance.log"
    threshold: 1.0  # 记录超过1秒的操作
  # 错误日志
  error:
    enabled: true
    path: "logs/errors.log"
    include_traceback: true

# 系统配置
system:
  # 工作目录
  work_dir: "."
  # 临时文件目录
  temp_dir: "temp"
  # 缓存目录
  cache_dir: "cache"
  # 最大内存使用（MB）
  max_memory: 1024
  # 清理临时文件
  cleanup_temp: true
  # 性能监控
  performance_monitoring:
    enabled: true
    interval: 60  # 监控间隔（秒）
    metrics:
      - "cpu_usage"
      - "memory_usage"
      - "disk_usage"
      - "network_io"

# 全局设置（与SystemConfig类字段对应）
debug_mode: false
performance_monitoring: true
auto_save_screenshots: false
screenshot_dir: "resources"
data_dir: "."
temp_dir: "temp"

# 安全配置
security:
  # 操作确认
  require_confirmation: false
  # 安全模式（限制危险操作）
  safe_mode: true
  # 操作记录
  audit_log:
    enabled: true
    path: "logs/audit.log"
  # API密钥加密
  encrypt_api_keys: true

# 开发配置
development:
  # 调试模式
  debug: false
  # 详细日志
  verbose: false
  # 模拟模式（不执行实际操作）
  simulation_mode: false
  # 性能分析
  profiling:
    enabled: false
    output_dir: "profiling"
  # 测试配置
  testing:
    mock_device: false
    test_data_dir: "tests/data"