# iPad自动化控制系统配置文件
# 重构版本 v2.0 配置示例

# 设备连接配置
connection:
  # 连接超时时间（秒）
  timeout: 30
  # 重试次数
  retry_count: 3
  # tunneld服务端口
  tunneld_port: 5000
  # 设备UDID（可选，留空自动检测）
  device_udid: ""
  # 连接模式（usb）
  connection_mode: "usb"
  
  # 截图服务配置
  screenshot:
    # 截图超时时间（秒）
    timeout: 15
    # 截图重试次数
    max_retries: 3
    # 重试间隔（秒）
    retry_interval: 2
    # 外部截图命令超时（秒）
    external_timeout: 10
    # 截图质量检查
    quality_check: true
    # 最小文件大小（字节）
    min_file_size: 1024

# 视觉识别配置
vision:
  # VLM配置
  vlm:
    enabled: true
    provider: "ollama"  # 可选: ollama, openai, anthropic
    
  # Ollama配置
  ollama_config:
    base_url: "http://localhost:11434"
    model: "qwen2.5vl:latest"
    timeout: 60
    max_retries: 3
    image_max_size: [800, 600]
    image_quality: 75
    
  # 模板匹配配置
  template_matching:
    enabled: true
    template_dir: "resources/templates"
    confidence_threshold: 0.6
    fallback_enabled: true
    fallback_threshold: 0.3
    
  # VLM API配置
  vlm_config:
    api_key: ""
    model: "qwen2.5vl:latest"
    max_tokens: 1000
    temperature: 0.1
  # 非极大值抑制阈值
  nms_threshold: 0.3
  # 最大检测数量
  max_detections: 50
  # 截图保存配置
  screenshot:
    save_enabled: true
    save_dir: "resources/screenshots"
    format: "png"
    quality: 95

# 自动化执行配置
automation:
  # 自动化后端（webdriver/pymobiledevice）
  backend: "webdriver"
  # WebDriverAgent配置
  webdriver:
    # WDA服务端口
    port: 8100
    # WDA服务地址
    host: "localhost"
    # 连接超时
    timeout: 60
    # 启动WDA服务
    auto_start: true
  # pymobiledevice配置
  pymobiledevice:
    # 触控延迟（秒）
    touch_delay: 0.1
    # 滑动持续时间（秒）
    swipe_duration: 0.5
  # 通用操作配置
  actions:
    # 操作间延迟（秒）
    delay: 0.5
    # 点击持续时间（秒）
    click_duration: 0.1
    # 长按持续时间（秒）
    long_press_duration: 1.0
    # 滑动速度（像素/秒）
    swipe_speed: 1000

# 任务管理配置
task:
  # 任务执行超时（秒）
  execution_timeout: 300
  # 最大并发任务数
  max_concurrent_tasks: 1
  # 任务重试次数
  retry_count: 3
  # 任务历史保留数量
  history_limit: 100
  # 条件检查间隔（秒）
  condition_check_interval: 1.0

# 异步分析配置
async_analysis:
  # 是否启用异步分析
  enabled: true
  # 最大并发分析任务数
  max_concurrent_analyses: 3
  # 分析历史记录限制
  history_limit: 100
  # 自动分析配置
  auto_analysis:
    enabled: false
    interval: 5.0  # 自动分析间隔（秒）
    priority: 0    # 自动分析任务优先级
  # 持续运行模式配置
  continuous_mode:
    enabled: false           # 是否启用持续运行模式
    default_interval: 60.0   # 默认分析间隔（秒）- 避免API调用超时
    min_interval: 30.0       # 最小分析间隔（秒）- 确保API调用稳定
    max_iterations: 0        # 默认最大运行次数（0表示无限制）
    auto_execute: false      # 是否自动执行高优先级建议
    priority_threshold: 0.7  # 高优先级建议阈值
    save_results: true       # 是否保存分析结果
    results_dir: "logs/continuous_results"  # 结果保存目录
  # 提示词优化配置
  prompt_optimization:
    enabled: true
    min_history_count: 5     # 最少历史记录数
    optimization_interval: 50 # 优化间隔（分析次数）
    auto_optimize: false     # 是否自动优化
  # 结果输出配置
  output:
    console_enabled: true    # 控制台输出
    file_enabled: true       # 文件输出
    file_path: "logs/analysis_results.log"
    max_elements_display: 5  # 最大显示元素数
    max_suggestions_display: 3 # 最大显示建议数

# 日志配置
logging:
  # 文件日志级别（DEBUG/INFO/WARNING/ERROR/CRITICAL）
  level: "DEBUG"
  # 控制台日志级别（DEBUG/INFO/WARNING/ERROR/CRITICAL）
  console_level: "INFO"
  # 日志格式
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  # 文件输出路径
  file_path: "logs/ipad_automation.log"
  # 文件大小限制
  max_file_size: "10 MB"
  # 备份文件数量
  backup_count: 5
  # 控制台输出
  console_output: true
  # 彩色输出
  colored_output: true
  # 性能日志
  performance:
    enabled: true
    path: "logs/performance.log"
    threshold: 1.0  # 记录超过1秒的操作
  # 错误日志
  error:
    enabled: true
    path: "logs/errors.log"
    include_traceback: true

# 系统配置
system:
  # 工作目录
  work_dir: "."
  # 临时文件目录
  temp_dir: "temp"
  # 缓存目录
  cache_dir: "cache"
  # 最大内存使用（MB）
  max_memory: 1024
  # 清理临时文件
  cleanup_temp: true
  # 性能监控
  performance_monitoring:
    enabled: true
    interval: 60  # 监控间隔（秒）
    metrics:
      - "cpu_usage"
      - "memory_usage"
      - "disk_usage"
      - "network_io"

# 全局设置（与SystemConfig类字段对应）
debug_mode: false
performance_monitoring: true
auto_save_screenshots: false  # 禁用自动保存，避免重复截图
screenshot_dir: "resources/screenshots"
data_dir: "."
temp_dir: "temp"
# 分析截图保存设置
save_analysis_screenshots: true  # 是否保存分析时的截图

# 安全配置
security:
  # 操作确认
  require_confirmation: false
  # 安全模式（限制危险操作）
  safe_mode: true
  # 操作记录
  audit_log:
    enabled: true
    path: "logs/audit.log"
  # API密钥加密
  encrypt_api_keys: true

# 提示词配置
prompt:
  # 提示词配置文件路径
  config_file: "prompts.yaml"
  # 是否启用提示词优化
  enable_optimization: true
  # 优化频率（使用次数阈值）
  optimization_frequency: 3  # 降低到3次，更容易触发优化
  # 是否缓存提示词
  cache_prompts: true
  # 是否回退到内置提示词
  fallback_to_builtin: true

# 开发配置
development:
  # 调试模式
  debug: false
  # 详细日志
  verbose: false
  # 模拟模式（不执行实际操作）
  simulation_mode: false
  # 性能分析
  profiling:
    enabled: false
    output_dir: "profiling"
  # 测试配置
  testing:
    mock_device: false
    test_data_dir: "tests/data"